// Generated by gencpp from file riki_msgs/Speed_compensation.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_SPEED_COMPENSATION_H
#define RIKI_MSGS_MESSAGE_SPEED_COMPENSATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct Speed_compensation_
{
  typedef Speed_compensation_<ContainerAllocator> Type;

  Speed_compensation_()
    : k(0)
    , scc(0)  {
    }
  Speed_compensation_(const ContainerAllocator& _alloc)
    : k(0)
    , scc(0)  {
  (void)_alloc;
    }



   typedef int32_t _k_type;
  _k_type k;

   typedef int32_t _scc_type;
  _scc_type scc;





  typedef boost::shared_ptr< ::riki_msgs::Speed_compensation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::Speed_compensation_<ContainerAllocator> const> ConstPtr;

}; // struct Speed_compensation_

typedef ::riki_msgs::Speed_compensation_<std::allocator<void> > Speed_compensation;

typedef boost::shared_ptr< ::riki_msgs::Speed_compensation > Speed_compensationPtr;
typedef boost::shared_ptr< ::riki_msgs::Speed_compensation const> Speed_compensationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::Speed_compensation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::Speed_compensation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::riki_msgs::Speed_compensation_<ContainerAllocator1> & lhs, const ::riki_msgs::Speed_compensation_<ContainerAllocator2> & rhs)
{
  return lhs.k == rhs.k &&
    lhs.scc == rhs.scc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::riki_msgs::Speed_compensation_<ContainerAllocator1> & lhs, const ::riki_msgs::Speed_compensation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace riki_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Speed_compensation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Speed_compensation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Speed_compensation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Speed_compensation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Speed_compensation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Speed_compensation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::Speed_compensation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0911bcab23d8937cd1ba25782127e119";
  }

  static const char* value(const ::riki_msgs::Speed_compensation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0911bcab23d8937cULL;
  static const uint64_t static_value2 = 0xd1ba25782127e119ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::Speed_compensation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/Speed_compensation";
  }

  static const char* value(const ::riki_msgs::Speed_compensation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::Speed_compensation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 k\n"
"int32 scc\n"
;
  }

  static const char* value(const ::riki_msgs::Speed_compensation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::Speed_compensation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.k);
      stream.next(m.scc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Speed_compensation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::Speed_compensation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::Speed_compensation_<ContainerAllocator>& v)
  {
    s << indent << "k: ";
    Printer<int32_t>::stream(s, indent + "  ", v.k);
    s << indent << "scc: ";
    Printer<int32_t>::stream(s, indent + "  ", v.scc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_SPEED_COMPENSATION_H
